---
abstract: 'Tapper - Common functions for all Tapper classes'
author:
  - 'AMD OSRC Tapper Team <tapper@amd64.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::Perl::Critic: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: freebsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tapper-Base
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Fcntl: 0
  LockFile::Simple: 0
  MooseX::Log::Log4perl: 0
  common::sense: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Tapper-Base
  repository: git://github.com/amd/Tapper-Base.git
version: 3.000004
